openapi: 3.1.0
info:
  title: FastAPI
  version: 0.1.0
paths:
  /api/cosine:
    get:
      summary: Get Cosine
      operationId: get_cosine_api_cosine_get
      parameters:
        - name: x
          in: query
          required: true
          schema:
            type: number
            description: Input value for cosine calculation
            title: X
          description: Input value for cosine calculation
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: number
                title: Response Get Cosine Api Cosine Get
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /api/surface:
    get:
      summary: Get Surface
      operationId: get_surface_api_surface_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                items:
                  items:
                    type: number
                  type: array
                type: array
                title: Response Get Surface Api Surface Get
components:
  schemas:
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
              - type: string
              - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
        - loc
        - msg
        - type
      title: ValidationError
