apiVersion: apps/v1
kind: Deployment
metadata:
  name: qc-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qc-server
  template:
    metadata:
      labels:
        app: qc-server
    spec:
      containers:
        - name: qc-server
          image: qc-server:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000