apiVersion: v1
kind: Service
metadata:
  name: qc-server
spec:
  type: NodePort
  selector:
    app: qc-server
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30080 # You can choose a port between 30000-32767